name: "Minha Composite Action"
description: "Uma nova composite action

inputs:
  my-input:
    description: "Input vindo do workflow"
    required: true
    default: ''

outputs:
  my-output: 
    value: ${{ stps.hello-wolrd-msg.outputs.output }}

runs:
  using: 'composite'
  steps:
    - name: Hello ${{ inputs.my.input }}
    - run: echo "Hello ${{ inputs.ny-input }}!"
    shell: bash

    - name: Send Output
      id: hello-world-msg
      run: echo "output=$(echo Hello ${{ inputs.my.input }})" >> $GITHUB OUTPUT
      shell: bash
