name : Hello World
on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: API_KEY
        run: echo "Usando a API_KEY ${{ env.API_KEY }}"
        env:
          API_KEY: valor         
